### ISSUE TITLE
Forest dirt tile color mismatch

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1236]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
All forest dirt tile look nice with no bad transitions.

##### Actual behavior
There are some forest dirt tiles that have a slightly different tint with a sharp and ugly transition.

It seems to affect tiles that have a “height” of 1, that is, they have a grass top and a dirt “finish” at the bottom.

Evidence in "Bouncy Coils" level:

https://satoshiupload.com/images/xIaxxdYiUL.png

But I have seen evidence in many other forest levels as well.

##### My guess

This could be tileset-related, rather than level-related. But this is only a theory. A GAME THEORY!!11!

##### Steps to reproduce actual behavior
1. Enter Forest World
2. Play lots of levels
3. Pay attention to all those dirt tiles

**Comment by weluvgoatz** [comment]
@HybridDog changed these files last, I assign him.

**Comment by Rusty-Box** [comment]
Odd. My tiles show the right tint. Maybe a similar issue than the bridge one.

**Comment by Wuzzy2** [comment]
FYI: My source for ST is a fresh `git clone`, NOT the downloadable archive.

**Comment by Wuzzy2** [comment]
I deleted my `config` file and then it was fixed! :-)

Closing.

**Comment by HybridDog** [comment]
Some of my forest roads brown looks wrong:
![t](https://user-images.githubusercontent.com/3192173/71482561-8800fb00-2803-11ea-93ea-c351ed576099.jpg)
I deleted the `config` and it still happened.

**Comment by Rusty-Box** [comment]
I don't quite get what this has to do with the original issue but okay... Anyway this one is caused by an actual tiling issue, so no `config` solution here. This has to be fixed on the worldmap itself.

**Comment by Wuzzy2** [comment]
Feel free to re-close and demand a new issue instead.

**Comment by Semphriss** [comment]
Both problems have been fixed (ladders were added), closing
