### ISSUE TITLE
tiles.strf bug

### ISSUE THREAD

**Issue by Hume2** [SuperTux/supertux#124]
I've previously installed SuperTux 0.3.4 on my Ubuntu platform and after that I downloaded SuperTux 0.3.5, but didn't installed it, because it wasn't in the Ubuntu resources. When SuperTux wants to load tiles.strf, it loads the 0.3.4 tiles.strf from a super secret mystic resource. Even when I remove tiles.strf from SuperTux 0.3.5, it runs too. I've also tried uninstalling SuperTux 0.3.4 and putting the 0.3.5 tiles.strf instead of 0.3.4 tiles.strf, but it had no effect. I've also looked for any other tiles.strf on my computer, but there wasn't any other.

When I set the tileset to tiles_.strf and then rename the tiles.strf to tiles_.strf, it works.

I know, that it's hard to reproduce, so is there a way how do I fix that at least for myself?

EDIT: It happens with abednego-level1.stl too.
Setting datadir doesn't have any effect.
I've also tried to install it, but then I couldn't run SuperTux from the instalation, but I could still run it from my built source. This had no effect too.

**Comment by tobbi** [comment]
Check the --datadir option. You can set the data dir for yourself.

**Comment by Hume2** [comment]
I've never done anything with options, could you tell me exact syntax or at least the command that I've to call?

**Comment by tobbi** [comment]
./supertux2 --datadir /path/to/directory or check ./supertux2 --help for all the options.

**Comment by Hume2** [comment]
./supertux2 doesn't seem to work. It says that it's invalid directory or file.

**Comment by tobbi** [comment]
You need to cd to the supertux directory first.

**Comment by Hume2** [comment]
./supertux2 --datadir data
It launches SuperTux, but everything is black and there's a menu in the center with blank menu items. However, the music is playing well. It seems that everything loads well, except the images.

**Comment by tobbi** [comment]
The graphics issue has been fixed. Please merge with latest master.

**Comment by Hume2** [comment]
SuperTux now displays correctly, but this bug remains. Could you reopen it then?

**Comment by Karkus476** [comment]
--datadir <directory> specifies the location of the data. Is supertux/data the correct directory?

**Comment by Hume2** [comment]
I got what caused this problem. SuperTux loaded the tiles.strf from the halloween addon all the time. I deleted it and it works well.

**Comment by Hume2** [comment]
It's all solved. I just had a mess in .supertux2.
