### ISSUE TITLE
Do not install external dependencies system-wide

### ISSUE THREAD

**Issue by akien-mga** [SuperTux/supertux#275]
Building SuperTux on Linux, after running make install I end up with many files from tinygettext and squirrel installed system-wide:

```
   /usr/include/tinygettext/dictionary.hpp
   /usr/include/tinygettext/dictionary_manager.hpp
   /usr/include/tinygettext/file_system.hpp
   /usr/include/tinygettext/iconv.hpp
   /usr/include/tinygettext/language.hpp
   /usr/include/tinygettext/log.hpp
   /usr/include/tinygettext/log_stream.hpp
   /usr/include/tinygettext/plural_forms.hpp
   /usr/include/tinygettext/po_parser.hpp
   /usr/include/tinygettext/tinygettext.hpp
   /usr/include/tinygettext/unix_file_system.hpp
   /usr/lib64/libsquirrel.a
   /usr/lib64/libtinygettext.a
   /usr/lib64/pkgconfig/tinygettext.pc
```

In my case it's static libraries as I built with ```-DBUILD_SHARED_LIBS=OFF```, which you should probably turn on by default anyway as external libraries should likely be bundled directly in the binary using static libs.

But whether it's static or shared libraries, they should not be installed system-wide as they would conflict with potentially existing system-wide libraries, and SuperTux does not need those headers, pkgconfig file and libraries at runtime.

**Comment by maths22** [comment]
I'll take care of this soon.

**Comment by Grumbel** [comment]
Same issue exist on Windows, the .msi binary contains header files and static libraries.

**Comment by maths22** [comment]
Fixed with c5adabfc0c5e484908f5269f26759edd1ff3a346

**Comment by Grumbel** [comment]
Problem isn't fixed yet:

    $ make install DESTDIR=/tmp/supertux-destdir/
    $ find /tmp/supertux-destdir/ -iname "*.so"
    /tmp/supertux-destdir/usr/local/lib/libtinygettext.so

**Comment by akien-mga** [comment]
@Grumbel In this case it's not a bug, if you build tinygettext as shared libraries, then you need to have it installed as it's only linked dynamically in the supertux binary. Typically you would build with ```BUILD_SHARED_LIBS=OFF``` in the CMake call to prevent that.

**Comment by Grumbel** [comment]
Yes, that's the bug. It should be statically linked without any user interaction.

**Comment by akien-mga** [comment]
Then we just need to add ```set(BUILD_SHARED_LIBS OFF)``` in CMakeLists.txt I guess.

**Comment by Grumbel** [comment]
Use of `ExternalProject_Add()` instead of `add_subdirectory()` seems to be more appropriate:

    include(ExternalProject)
    set(TINYGETTEXT_PREFIX ${CMAKE_BINARY_DIR}/tinygettext_inst/)
    ExternalProject_Add(tinygettext
      SOURCE_DIR "${CMAKE_SOURCE_DIR}/external/tinygettext/"
      BUILD_COMMAND cmake
      CMAKE_ARGS
      -DBUILD_SHARED_LIBS=OFF
      -DHAVE_SDL=ON
      -DCMAKE_INSTALL_PREFIX=${TINYGETTEXT_PREFIX})

    link_directories(${TINYGETTEXT_PREFIX}/libs)
    include_directories(${TINYGETTEXT_PREFIX}/include)

**Comment by maths22** [comment]
Fixed with some commit a while ago
