### ISSUE TITLE
[Crash]: Crashed when completed the level The Castle of Nolok

### ISSUE THREAD

**Issue by Willaw-Corona** [SuperTux/supertux#3399]
### SuperTux Version

v0.6.3 dev - 138a838 (master) (CI ARTIFACT)

### System Information

Linux 6.17.6-300.fc43.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 29 20:10:51 UTC 2025 x86_64

### Steps To Reproduce Crash

I certainly don't know how, i just completed the level The Castle of Nolok and that's it

### Debugging Information (Stacktrace)

```shell
supertux2(+0x402f10) [0x55b552dd3f10]
supertux2(+0x40463b) [0x55b552dd563b]
/lib64/libc.so.6(+0x1a2c0) [0x7f8317dfa2c0]
supertux2(+0x42ebd0) [0x55b552dffbd0]
supertux2(+0x515553) [0x55b552ee6553]
supertux2(+0x51c607) [0x55b552eed607]
supertux2(+0x21f561) [0x55b552bf0561]
supertux2(+0x4e4d18) [0x55b552eb5d18]
supertux2(+0x433438) [0x55b552e04438]
supertux2(+0x4deb0a) [0x55b552eafb0a]
supertux2(+0x4dfa99) [0x55b552eb0a99]
supertux2(+0x4dfdd0) [0x55b552eb0dd0]
supertux2(+0x456ceb) [0x55b552e27ceb]
supertux2(main+0x64) [0x55b552b36a64]
/lib64/libc.so.6(+0x35b5) [0x7f8317de35b5]
/lib64/libc.so.6(__libc_start_main+0x88) [0x7f8317de3668]
supertux2(+0x165c35) [0x55b552b36c35]
```

### Guidelines For Reporting Issues

- [x] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [x] I have verified this isn't an issue that's already been reported.
- [x] I have verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), or an issue about unintended behavior or a feature request, but rather an actual crash ─ that is, the game closed unexpectedly.
- [x] I have verified this issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [x] In this report, I have only included details about **one** (1) crash.
- [x] If I make a mistake while submitting this report, I agree to use the "Edit" feature to correct it, instead of closing this issue and opening a new one.

**Comment by huntekye** [comment]
Can you check the build artifact from #3395 ? This problem should be fixed by it.

**Comment by Narre** [comment]
That PR "fixes" the problem by not calling the problematic function, however, the crash is still very real. It happens when calling `load_level()` via scripting.

**Comment by Hypernoot** [comment]
fixed by #3395
