### ISSUE TITLE
Glitch on Light and Magic

### ISSUE THREAD

**Issue by Tlaloc1** [SuperTux/supertux#469]
**SuperTux version: 0.4.0-717 (Although it has been tested with other versions, and other levels)**
**System information:** *(MacBook Pro, 2.5 GHz Intel Core i5)*
On Light and Magic, there is glitch that allows the White lantern that allows every magic block to be lit up. Using a bug though, the lantern can be clipped through a wall.
Video Showcasing the glitch:
https://youtu.be/K166OO4y8yA

**Comment by IndianaTux** [comment]
I thought this glitch was fixed as of issue #335 .

**Comment by Tlaloc1** [comment]
@IndianaTux Just tested this with the latest version (0.4.0-732) and the glitch still works, so it wasn't fixed.

**Comment by Karkus476** [comment]
Should the hitbox size be changed while holding a lantern then?

**Comment by tobbi** [comment]
That sounds like a good solution, actually. Can you do it, Karkus?

**Comment by tobbi** [comment]
I'm on it, now.
