### ISSUE TITLE
Small list of editor related issues I came across

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#949]
- [x] 1. Certain badguys don't show the right animation when being placed in the editor.
(Zeekling, Mole, Spider mite, Plant, Smart Block (has Mr. Iceblock sprites), Sleeping spiky (has spiky walk animation), Sleeping live fire & dormant live fire (both have live fire walking animation), Ice flame, Totem, Yeti stalactite & stalactite (both invisible), Leaf shot (has kamikaze snowball sprites).
- [x] 2. Path nodes do not follow immediately when moving the moveable object around (they reappear at the right position when selecting the object again though).
- [x] 3. When changing the alpha values of tilemaps it is not shown right after the change has been done. The level must be saved and loaded again to see the change in the editor.
- [ ] 4. Tilemaps and coin objects can not be set to follow paths because if the level is loaded again after saving, all are set back to not follow paths and get automatically positioned to the coordinates x=0 and y=0.

**Comment by Grumbel** [comment]
1. fixed in eb46c20d0

3. fixed in 59864138e

**Comment by Rusty-Box** [comment]
@Grumbel Stalactite & yeti stalactite are still invisible and mole, totem, sleeping spiky, sleeping live fire & dormant live fire still show wrong animations in the editor. Issue nr. 2 is still not fixed.

**Comment by Grumbel** [comment]
I think I fixed it all, feel free to reopen if there is something else.

**Comment by Rusty-Box** [comment]
@Grumbel All are fixed except for a part of nr. 4. The path nodes and objects are in sync but the game does not save that a movable coin or tilemap is set to follow paths and they still get automatically positioned to the coordinates x=0 and y=0 after saving and loading the level again.

**Comment by Rusty-Box** [comment]
Bugs are all fixed now. Closing this.
